- name: Check enabled repositories
  shell: subscription-manager repos --list-enabled | grep Enabled | wc -l
  register: rhsm_enabled
  changed_when: false

- name: Disable all RHSM repositories
  command: subscription-manager repos --disable='*'
  when: rhsm_enabled.stdout != "5"

- name: Enable OpenShift repositories
  command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
  when: rhsm_enabled.stdout != "5"

- name: Download required packages
  command: yum -y install wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct vim atomic-openshift-utils docker-1.13.1

- name: Update packages
  command: yum -y update

- name: Start/enable docker
  systemd:
    name: docker
    state: started
    enabled: true