- name: Check enabled repositories
  shell: subscription-manager repos --list-enabled | grep Enabled | wc -l
  register: rhsm_enabled
  changed_when: false

- name: Disable all RHSM repositories
  command: subscription-manager repos --disable='*'
  when: rhsm_enabled.stdout != "5"

- name: Enable OpenShift repositories
  command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
  when: rhsm_enabled.stdout != "5"

- name: Download required packages
  command: yum -y install wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct vim ansible atomic-openshift-utils screen nfs-utils dnsmasq lvm2

- name: Update packages
  command: yum -y update

- name: Start/enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - nfs-server
  - dnsmasq

- name: Create NFS export directory
  file:
    state: directory
    owner: nfsnobody
    group: nfsnobody
    mode: 0777
    path: "{{ nfs.export_dir }}"

- name: Create NFS export subdirectories
  file:
    state: directory
    owner: nfsnobody
    group: nfsnobody
    mode: 0777
    path: "{{ item.mountpath }}"
  with_items: "{{ nfs.exports }}"

- name: Create logical volume group for nfs exports
  lvg:
    pvs: "{{ nfs.pv }}"
    state: present
    vg: "{{ nfs.vg }}"

- name: Create logical volumes for nfs exports
  lvol:
    vg: "{{ nfs.vg }}"
    size: "{{ item.size }}"
    lv: "{{ item.lv }}"
  with_items: "{{ nfs.exports }}"

- name: Format filesystems for nfs exports
  filesystem:
    dev: "/dev/mapper/{{ nfs.vg }}-{{ item.lv }}"
    fstype: "{{ item.fstype }}"
  with_items: "{{ nfs.exports }}"

- name: Mount nfs exports
  mount:
    state: mounted
    path: "{{ item.mountpath }}"
    src: "/dev/mapper/{{ nfs.vg }}-{{ item.lv }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.mountopts }}"
  with_items: "{{ nfs.exports }}"

- name: Create /etc/exports
  template:
    dest: /etc/exports
    src: templates/exports
    mode: 0664
  notify:
  - Restart nfs-server

- name: Create dnsmasq configuration
  copy:
    src: files/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    backup: yes
  notify:
  - Restart dnsmasq

- name: Create /etc/hosts
  copy:
    src: files/etc-hosts
    dest: /etc/hosts
    backup: yes

- name: Create OpenShift hosts file
  copy:
    src: files/hosts
    dest: "/home/{{ user }}/hosts"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664

- name: Create ansible.cfg
  copy:
    src: files/ansible.cfg
    dest: "/home/{{ user }}/ansible.cfg"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664