---
- hosts: localhost
  become: no
  gather_facts: no
  vars:
    host_dir: "../.hosts"
    host_image_dir: "../.images"
  vars_files:
  - ../vars/environment.yml
  tasks:
  - name: Get current list of vms
    shell: virsh --connect=qemu:///system list
    changed_when: false
    register: vm_list

  - name: Stop vms
    shell: "virsh --connect=qemu:///system destroy --domain {{ item.key }}"
    when: vm_list.stdout is search(item.key)
    with_dict: "{{ nodes }}"

  - name: Undefine vms
    shell: "virsh --connect=qemu:///system undefine --domain {{ item.key }}"
    when: vm_list.stdout is search(item.key)
    with_dict: "{{ nodes }}"

  - name: Get current list of storage pools
    shell: virsh --connect=qemu:///system pool-list --all
    changed_when: false
    register: pool_list

  - name: Stop storage pools
    shell: "virsh --connect=qemu:///system pool-destroy {{ item.key }}"
    when: pool_list.stdout is search(item.key)
    with_dict: "{{ nodes }}"

  - name: Undefine storage pools
    shell: "virsh --connect=qemu:///system pool-undefine {{ item.key }}"
    when: pool_list.stdout is search(item.key)
    with_dict: "{{ nodes }}"

  - name: Get current list of networks
    shell: virsh --connect=qemu:///system net-list
    changed_when: false
    register: net_list

  - name: Stop and delete network
    block:
    - shell: "virsh --connect=qemu:///system net-destroy {{ network.name }}"
    - shell: "virsh --connect=qemu:///system net-undefine {{ network.name }}"
    when: net_list.stdout is search(network.name)

  - name: Delete files
    file:
      state: absent
      path: "{{ host_dir }}"

- hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
  - ../vars/environment.yml
  tasks:
  - name: Clean /etc/hosts
    blockinfile:
      state: absent
      path: /etc/hosts
      block: |
        {{ nodes['ans.lab.local']['ip'] }} ans ans.lab.local
        {{ nodes['mas.lab.local']['ip'] }} mas mas.lab.local
        {{ nodes['inf.lab.local']['ip'] }} inf inf.lab.local
        {{ nodes['app.lab.local']['ip'] }} app app.lab.local
        {{ nodes['mas.lab.local']['ip'] }} ocp.lab.local
  
  - name: Remove SSH script
    file:
      state: absent
      path: "{{ lookup('env','HOME') }}/bin/cluster-ssh"