#!/usr/local/bin/ansible-playbook
---
- name: Create host groups
  hosts: localhost
  become: no
  gather_facts: no
  tasks:
  - name: Create host groups
    tags:
    - rhsm
    add_host:
      groups: "{{ item.value.groups | join(',') }}"
      name: "{{ item.value.ip }}"
    changed_when: false
    with_dict: "{{ cluster_nodes }} "
    
- hosts: control:masters:infras:computes
  become: yes
  gather_facts: no
  tags:
  - rhsm
  tasks:
  - name: Deregister from RHSM
    redhat_subscription:
      state: absent

- hosts: localhost
  gather_facts: no
  vars:
    host_environment_dir: "{{ host_dir }}/{{ network.name }}"
  tasks:
  - name: Get current list of vms
    shell: virsh --connect=qemu:///system list
    changed_when: false
    register: vm_list

  - name: Stop vms
    shell: "virsh 
            --connect=qemu:///system destroy 
            --domain {{ item.value.hostname }}"
    when: vm_list.stdout is search(item.value.hostname)
    with_dict: "{{ cluster_nodes }}"

  - name: Undefine vms
    shell: "virsh 
            --connect=qemu:///system undefine 
            --domain {{ item.value.hostname }}"
    when: vm_list.stdout is search(item.value.hostname)
    with_dict: "{{ cluster_nodes }}"

  - name: Get current list of storage pools
    shell: virsh --connect=qemu:///system pool-list --all
    changed_when: false
    register: pool_list

  - name: Stop storage pools
    shell: "virsh --connect=qemu:///system pool-destroy {{ item.value.hostname }}"
    when: pool_list.stdout is search(item.value.hostname)
    with_dict: "{{ cluster_nodes }}"

  - name: Undefine storage pools
    shell: "virsh --connect=qemu:///system pool-undefine {{ item.value.hostname }}"
    when: pool_list.stdout is search(item.value.hostname)
    with_dict: "{{ cluster_nodes }}"

  - name: Get current list of networks
    shell: virsh --connect=qemu:///system net-list
    changed_when: false
    register: net_list

  - name: Stop and delete network
    block:
    - shell: "virsh --connect=qemu:///system net-destroy {{ network.name }}"
    - shell: "virsh --connect=qemu:///system net-undefine {{ network.name }}"
    when: net_list.stdout is search(network.name)

  - name: Delete files
    file:
      state: absent
      path: "{{ host_environment_dir }}"
  
  - name: Delete SSH aliases
    blockinfile:
      path: "{{ lookup('env', 'HOME') }}/.ssh/config"
      state: absent
      marker: "# {{ network.name }} OpenShift cluster"

  - name: Remove SSH script
    file:
      state: absent
      path: "{{ lookup('env','HOME') }}/bin/cluster-ssh"